apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "jenkins"
    meta.helm.sh/release-namespace: "devops-test"
  name: devops-test-pvc
  namespace: devops-test
  app.kubernetes.io/managed-by: "Helm"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: devops-test-sc
  resources:
    requests:
      storage: 10Gi