apiVersion: v1
kind: Service
metadata:
  name: artifactory-nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 30200
      targetPort: 80
      protocol: TCP
      name: http-nginx
  selector:
    app: nginx
