apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: nginx
      name: artifactory-nginx
    spec:
      serviceAccountName: artifactory-nginx
      ports:
      - name: http-nginx
        containerPort: 80
        protocol: TCP
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/
          readOnly: true
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config